### ISSUE TITLE
Enable Background Bluring after Video activation

### ISSUE THREAD

**Issue by MKr4zy** [drlight17/bbb-html5client-blur-background#1]
Currently one has to activate the Blurring option before activating Video.

This is not really an Issue, just out of curiosity:
would it be possible to activate the blurring after activating Video?
Otherwise this is a really usefull addon!
Well done!

**Comment by drlight17** [comment]
Thank you!
When this was developed I planned to make UI algorith as you asked. But there were some troubles that significantly increased the code difficulty. Now the new version with mediapipe support is being developed (this will bring significant performance boost especially on the mobile devices). Maybe I will try to make some changes in UI with this release.

**Comment by drlight17** [comment]
With [new bbb 2.4alpha-2 functionaly ](https://docs.bigbluebutton.org/2.4/new.html#webcam-background-blur) I close this issue and developing of this repo.
